In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("energydata_complete.csv")
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [3]:
df.shape

(19735, 29)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [5]:
df.describe()

Appliances        lights            T1          RH_1            T2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958      3.801875     21.686571     40.259739     20.341219   
std      102.524891      7.935988      1.606066      3.979299      2.192974   
min       10.000000      0.000000     16.790000     27.023333     16.100000   
25%       50.000000      0.000000     20.760000     37.333333     18.790000   
50%       60.000000      0.000000     21.600000     39.656667     20.000000   
75%      100.000000      0.000000     22.600000     43.066667     21.500000   
max     1080.000000     70.000000     26.260000     63.360000     29.856667   

               RH_2            T3          RH_3            T4          RH_4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      40.420420     22.267611     39.242500     20.855335     39.026904   
std        4.069813      2.006111      3.254576      2.042884      4.341321   
min       20.463333     17.200000     28.766667     15.100000     27.660000   
25%       37.900000     20.790000     36.900000     19.530000     35.530000   
50%       40.500000     22.100000     38.530000     20.666667     38.400000   
75%       43.260000     23.290000     41.760000     22.100000     42.156667   
max       56.026667     29.236000     50.163333     26.200000     51.090000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 28 columns]

In [6]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   date         19735 non-null  datetime64[ns]
 1   Appliances   19735 non-null  int64         
 2   lights       19735 non-null  int64         
 3   T1           19735 non-null  float64       
 4   RH_1         19735 non-null  float64       
 5   T2           19735 non-null  float64       
 6   RH_2         19735 non-null  float64       
 7   T3           19735 non-null  float64       
 8   RH_3         19735 non-null  float64       
 9   T4           19735 non-null  float64       
 10  RH_4         19735 non-null  float64       
 11  T5           19735 non-null  float64       
 12  RH_5         19735 non-null  float64       
 13  T6           19735 non-null  float64       
 14  RH_6         19735 non-null  float64       
 15  T7           19735 non-null  float64       
 16  RH_7

Question 17
From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the Root Mean Squared error in three D.P?

In [14]:
X = df[['T2']]
y = df['T6']

In [15]:
y

0         7.026667
1         6.833333
2         6.560000
3         6.433333
4         6.366667
           ...    
19730    24.796667
19731    24.196667
19732    23.626667
19733    22.433333
19734    21.026667
Name: T6, Length: 19735, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(
X,
y,
test_size=0.2,
random_state=42)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [20]:
y_pred = model.predict(X_test)
y_pred

array([ 2.15562488, 10.01834433,  1.87348764, ..., 14.12418366,
       13.30216726, 20.95487478])

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [22]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
round(rmse,3)

3.633

Remove the following columns: [“date”, “lights”]. The target variable is “Appliances”. Use a 70-30 train-test set split with a  random state of 42 (for reproducibility). Normalize the dataset using the MinMaxScaler (Hint: Use the MinMaxScaler fit_transform and transform methods on the train and test set respectively). Run a multiple linear regression using the training set. Answer the following questions:

What is the Mean Absolute Error (in three decimal places) for the  training set?

In [23]:
df['date'] = df['date'].astype('int64')

In [24]:
X = df[['date', 'lights']]
y= df['Appliances']

In [25]:
X_train,X_test,y_train,y_test = train_test_split(
X,
y,
test_size=0.3,
random_state=42)

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler = MinMaxScaler().fit(X_train)
scaler1 = MinMaxScaler().fit(X_test)

In [28]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
model =LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [30]:
y_pred = model.predict(X_test)
y_pred

array([ 87.43532363, 110.78441272,  87.50092088, ...,  88.63549421,
       167.00368516,  88.67951341])

In [31]:
y_mean = y_train.mean()
y_baseline_pred = [y_mean] * len(y_train)

In [32]:
Mse_train = mean_squared_error(y_train,y_baseline_pred)
rmse_train = np.sqrt(Mse_train)
MAE_train = mean_absolute_error(y_train,y_baseline_pred)
print('MAE Train:', round(MAE_train, 3))
print('MSE Train :', round(Mse_train,3 ))
print('RMSE Train:',round(rmse_train,3))

MAE Train: 60.569
MSE Train : 10600.056
RMSE Train: 102.957


In [33]:
Mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(Mse)
MAE = mean_absolute_error(y_test, y_pred)
print('MAE Test:', round(MAE, 3))
print('MSE Test :', round(Mse,3 ))
print('RMSE Test:',round(rmse,3))

MAE Test: 58.434
MSE Test : 9885.594
RMSE Test: 99.426


Train a ridge regression model with default parameters. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [34]:
from sklearn.linear_model import Ridge

In [35]:
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train,y_train)

Ridge(alpha=0.5)

In [36]:
y_pred = ridge_reg.predict(X_test)
y_pred

array([ 87.46605173, 110.75360446,  87.53130789, ...,  88.65998183,
       166.80029778,  88.70377214])

In [37]:
Ridge_Mse = mean_squared_error(y_test,y_pred)
Ridge_rmse = np.sqrt(Mse)
Ridge_MAE = mean_absolute_error(y_test, y_pred)
print('MAE Test:', round(Ridge_MAE, 3))
print('MSE Test :', round(Ridge_Mse,3 ))
print('RMSE Test:',round(Ridge_rmse,3))

MAE Test: 58.435
MSE Test : 9885.651
RMSE Test: 99.426


In [38]:
from sklearn.linear_model import Lasso

In [39]:
Lasso_reg = Lasso(alpha=0.001)
Lasso_reg.fit(X_train,y_train)

Lasso(alpha=0.001)

In [40]:
y_pred = Lasso_reg.predict(X_test)
y_pred

array([ 87.44084745, 110.78348191,  87.5063015 , ...,  88.63839818,
       166.96906158,  88.68232129])

In [41]:
Lasso_Mse = mean_squared_error(y_test,y_pred)
Lasso_rmse = np.sqrt(Mse)
Lasso_MAE = mean_absolute_error(y_test, y_pred)
print('MAE Test:', round(Lasso_MAE, 3))
print('MSE Test :', round(Lasso_Mse,3 ))
print('RMSE Test:',round(Lasso_rmse,3))

MAE Test: 58.434
MSE Test : 9885.614
RMSE Test: 99.426


In [44]:
# comparing the effects of Regularisation
def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns= ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_weights = get_weights_df(model, X_train, "Linear Model Weights")
Ridge_weights = get_weights_df(ridge_reg, X_train, "Ridge Model Weights")
lasso_weights = get_weights_df(lasso_reg, X_train, "Lasso Model Weights")

final_weights = pd.merge(linear_weights, Ridge_weights, on= 'Features')
final_weights = pd.merge(final_weights, lasso_weights, on= 'Features')

AttributeError: 'numpy.ndarray' object has no attribute 'columns'